#!/usr/bin/env bun
import { parseArgs } from "util";
import { stringify as toYaml } from "yaml";

const { values, positionals } = parseArgs({
  args: Bun.argv.slice(2),
  options: {
    output: { type: "string", short: "o", default: "urls.yaml" },
    depth: { type: "string", short: "d", default: "3" },
    concurrency: { type: "string", short: "c", default: "3" },
    include: { type: "string", default: "" },
    exclude: { type: "string", default: "" },
  },
  allowPositionals: true,
});

const rootUrl = positionals[0];
if (!rootUrl) {
  console.error("Usage: crawl.ts <root-url> [options]");
  console.error("  -o, --output <file>     Output YAML path (default: urls.yaml)");
  console.error("  -d, --depth <n>         Max crawl depth (default: 3)");
  console.error("  -c, --concurrency <n>   Concurrent tabs (default: 3)");
  console.error("  --include <pattern>     Include URL pattern");
  console.error("  --exclude <pattern>     Exclude URL pattern");
  process.exit(1);
}

const maxDepth = parseInt(values.depth!, 10);
const concurrency = parseInt(values.concurrency!, 10);
const outputPath = values.output!;
const includePattern = values.include || "";
const excludePattern = values.exclude || "";

const rootOrigin = new URL(rootUrl).origin;

function isSameOrigin(url: string): boolean {
  try {
    return new URL(url).origin === rootOrigin;
  } catch {
    return false;
  }
}

function normalizeUrl(url: string): string {
  try {
    const u = new URL(url);
    u.hash = "";
    // Remove trailing slash for consistency (except root)
    if (u.pathname !== "/" && u.pathname.endsWith("/")) {
      u.pathname = u.pathname.slice(0, -1);
    }
    return u.toString();
  } catch {
    return url;
  }
}

function matchesPattern(url: string, pattern: string): boolean {
  if (!pattern) return true;
  const regex = new RegExp(
    pattern.replace(/\*/g, ".*").replace(/\?/g, "."),
  );
  return regex.test(url);
}

function shouldInclude(url: string): boolean {
  if (includePattern && !matchesPattern(url, includePattern)) return false;
  if (excludePattern && matchesPattern(url, excludePattern)) return false;
  // Skip common non-page resources
  const skip = /\.(png|jpg|jpeg|gif|svg|ico|css|js|woff2?|ttf|eot|pdf|zip|tar|gz)$/i;
  if (skip.test(new URL(url).pathname)) return false;
  return true;
}

async function ab(args: string[]): Promise<string> {
  const proc = Bun.spawn(["agent-browser", ...args], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const output = await new Response(proc.stdout).text();
  await proc.exited;
  // Strip ANSI escape codes
  return output.replace(/\x1b\[[0-9;]*m/g, "").trim();
}

async function extractLinks(pageUrl: string): Promise<string[]> {
  await ab(["open", pageUrl]);
  // Use sleep instead of networkidle — many SPAs never reach idle
  await Bun.sleep(3000);

  // Extract all links via JavaScript
  const js = `JSON.stringify(Array.from(document.querySelectorAll('a[href]')).map(a => a.href).filter(h => h.startsWith('http')))`;
  const raw = await ab(["eval", js]);

  try {
    // Output may be wrapped in quotes — unwrap if needed
    const cleaned = raw.startsWith('"') ? JSON.parse(raw) : raw;
    const links: string[] = JSON.parse(cleaned);
    return links
      .map(normalizeUrl)
      .filter(isSameOrigin)
      .filter(shouldInclude);
  } catch {
    return [];
  }
}

// BFS crawl
const visited = new Set<string>();
const queue: Array<{ url: string; depth: number }> = [
  { url: normalizeUrl(rootUrl), depth: 0 },
];
visited.add(normalizeUrl(rootUrl));

console.log(`Crawling ${rootUrl} (max depth: ${maxDepth})...`);

while (queue.length > 0) {
  // Process batch
  const batch = queue.splice(0, concurrency);

  const results = await Promise.all(
    batch.map(async ({ url, depth }) => {
      console.log(`  [depth=${depth}] ${url}`);
      if (depth >= maxDepth) return [];

      try {
        const links = await extractLinks(url);
        return links
          .filter((link) => !visited.has(link))
          .map((link) => {
            visited.add(link);
            return { url: link, depth: depth + 1 };
          });
      } catch (e) {
        console.error(`  [error] ${url}: ${e}`);
        return [];
      }
    }),
  );

  for (const newEntries of results) {
    queue.push(...newEntries);
  }
}

// Sort URLs for consistent output
const sortedUrls = Array.from(visited).sort();

console.log(`\nFound ${sortedUrls.length} URLs`);

// Write YAML
const today = new Date().toISOString().split("T")[0];
const yamlContent = [
  `# Generated by site-to-yaml`,
  `# Source: ${rootUrl}`,
  `# Date: ${today}`,
  toYaml({ urls: sortedUrls }),
].join("\n");

await Bun.write(outputPath, yamlContent);
console.log(`Written to ${outputPath}`);
